before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: ./main.go
    binary: aws-vault-scg
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: aws-vault-scg
    goarm: "6"
    tap:
      owner: Gympass
      name: homebrew-tools
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/Gympass/aws-vault-scg/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: formula

